### ISSUE TITLE
question regarding release version for 1.11.2

### ISSUE THREAD

**Issue by SDUBZ** [elytra/ThermionicsWorld#1]
hey was just wondering when a release jar is coming out or is this project on stand by for a bit?

**Comment by exaskye** [comment]
The mod isn't completely finished, but there's a build available at https://endless.blue/files/ThermionicsWorld-MC1.11.2_ver1.0.3.jar - this is the version we use in Fondue 6.

**Comment by SDUBZ** [comment]
oh thanks man you the best team around with questions i swear :D

**Comment by SDUBZ** [comment]
also good job on website @unascribed i love the design

**Comment by falkreon** [comment]
Unascribed is correct, but I really should tidy the code up and put an "official" release up here just for completeness' sake.
