### ISSUE TITLE
Release for 1.12.2?

### ISSUE THREAD

**Issue by Vyraal1** [elytra/ThermionicsWorld#2]
Hi,

Sorry for the necro but I was curious to check this mod out for a 1.12.2 pack I'm making. I saw that there isn't an released version yet there on GH, so I was wondering if this is still being worked on.  I'm mostly interested in this mod because I wanted to add exploratory content to the Nether, and loved the description of what you had so far.

Also I was led here from the[ GlassHearts imgur album ](https://imgur.com/a/gZu42), so I apologize if there is some main site that I missed that has all of the release information.

**Comment by LemmaEOF** [comment]
Hi! I'm not the main dev, but I am part of the Elytra team.
[ThermionicsWorld is in 1.12](https://github.com/elytra/ThermionicsWorld/commit/4747824b435c48f70e41b88f5ba43dad6f08a104)! However, it's not that tested for stability yet. You can find development builds of all Elytra builds on our Jenkins, and [here](https://ci.elytradev.com/job/elytra/job/ThermionicsWorld/job/master/)'s the one for Thermionics World. Make a backup of your stuff just in case, and don't be surprised if it's finnicky or crashy, but you can definitely test it out. If you find any issues, please let us know. Thanks!

**Comment by exaskye** [comment]
Boundarybreaker is correct (other than possibly stability; Falk may have
just not had a chance to make a release)

I'm the Glass Hearts dev, and Elytra "curator", for lack of a better term
(I'm responsible for websites and such) - we're *supposed* to have a New
Cool Website I could point you to but I haven't gotten around to doing
it... :P

Might do it today.

**Comment by falkreon** [comment]
Whoops. Yeah, the 1.12 build B0undary linked is already tested and stable, just doesn't have a release published. Just needs a rebuild for 1.12.2 to make sure it plays well with others, I'll do that now.

**Comment by falkreon** [comment]
Release is out, thanks for pointing this out to me! ^_^
